# Generated by Django 3.0.8 on 2021-10-21 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminLTE', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
    ]
